global:
  environment: dev
  chart:
    # -- Github repositroy it resides in
    repo: https://github.com/Oran901/gitOpsPoke.git
    # -- Branch/Commit/Tag that we are looking at
    targetRevision: HEAD
    # -- Points towards the values file used by the environment
front:
  tag: "df6aa0a7d6e379946ea5c08b5de230c5fdee4a1e"

